# Generated by Django 5.1.3 on 2024-11-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('duration', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(default='/images/default.png', upload_to='images/user/')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(default='/images/default.png', upload_to='images/user/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hash_senha', models.CharField(max_length=512)),
                ('foto', models.ImageField(default='/images/default.png', upload_to='images/user/')),
            ],
        ),
    ]
