# Generated by Django 5.1.4 on 2024-12-06 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_curso_estoque_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 12, 6)),
            preserve_default=False,
        ),
    ]
